# File Basic Pods:
# Arquivo de configuração para criação de um POD
apiVersion: 'v1'
kind: 'Pod'
metadata:
  name: 'myapp-pod'
  label:
        app: 'myapp'
        type: 'front-end'

spec:
  containers:
    - name: 'nginx-container'
      image: 'nginx'