# File Replication-controller.yml
# Arquivo de configuração:

apiVersion: apps/v1
kind: Replicaset
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: 'front-end'
  spec:
  template:

  metadata:
    name: 'myapp-pod'
    labels:
        app: myapp
        type: 'frony-end'
    spec:
      containers:
      - name: 'nginx-container'
        image: 'nginx'

replicas: 3 
selector:
    matchLabels:
        type: font-end

















